### ISSUE TITLE
Possibility to selfhost

### ISSUE THREAD

**Issue by NUCL3ARN30N** [HSchuette/mailmask#63]
Hi,
Is there the possibility to selfhost this service with my own domain?
Also is there the option to use another cloud or own server for this?

Thank you!

**Comment by HSchuette** [comment]
Hey @NUCL3ARN30N!
Sadly there is no way to host mailmask on another cloud provider or on your own server. When I implemented this, I heavily relied on Amazons SES service to send out the mails. 
There should be ways to selfhost a mail forwarding service but I haven't looked into this that much.
